package com.mycompany.agendaturnos;
// Generated 01/12/2017 19:43:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private int idTurno;
     private Cliente cliente;
     private String descripcion;
     private Date fecha;

    public Turno() {
    }

	
    public Turno(int idTurno, Cliente cliente) {
        this.idTurno = idTurno;
        this.cliente = cliente;
    }
    public Turno(int idTurno, Cliente cliente, String descripcion, Date fecha) {
       this.idTurno = idTurno;
       this.cliente = cliente;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public int getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(int idTurno) {
        this.idTurno = idTurno;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


